# Pre-Commit Configuration File: https://pre-commit.com
---
exclude: ^deployment/
repos:
  - repo: local
    hooks:
      - id: helm-maintainers
        name: update helm maintainers
        entry: uv run python -m deployments.maintainers
        language: system
        pass_filenames: false
        stages: [pre-commit, post-commit]
        always_run: true
      - id: helm-inventory
        name: update helm inventory
        entry: uv run python -m deployments.inventory
        language: system
        pass_filenames: false
        stages: [pre-commit, post-commit]
        always_run: true
  # Commitizen Configuration
  # This configuration will add commitizen to your pre-commit hooks and will run it on commit-msg stage
  # of the git commit process.
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  # Pre-Commit Hooks Configuration
  # This configuration will add pre-commit hooks to your pre-commit hooks and will run it on pre-commit stage
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Prevent giant files from being committed.
      - id: check-added-large-files
      # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-case-conflict
      # Checks that non-binary executables have a proper shebang.
      - id: check-executables-have-shebangs
      # Attempts to load all json files to verify syntax.
      - id: check-json
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything.
      - id: check-symlinks
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml
        exclude: ^helm/
        args: [--allow-multiple-documents, --unsafe]
      # Attempts to load all xml files to verify syntax.
      - id: check-xml
      # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: debug-statements
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
      # Trims trailing whitespace.
      - id: trailing-whitespace
      # Checks for private key files.
      - id: detect-private-key
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: check for secrets
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
        name: helm lint
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        name: helm docs update
        args: [--chart-search-root=./helm, --skip-version-footer]
