apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ac.fullname" . }}-config
  labels:
    {{- include "ac.labels" . | nindent 4 }}
data:
  ac.properties: |-
    org.opencadc.ac.resourceID = {{ required "ac: application.resourceID is required" .Values.application.resourceID }}
{{- range .Values.application.readUsers }}
    org.opencadc.ac.readUser = {{ . }}
{{- end }}

  ac-group-names.properties: |-
    # Reserved group-name prefixes.
{{- $rules := .Values.application.groupNameRules | default dict }}
{{- range $prefix := keys $rules | sortAlpha }}
    {{ $prefix }} = {{ index $rules $prefix }}
{{- end }}

  ac-domains.properties: |-
    domains = {{ join " " .Values.application.domains }}

  cadc-registry.properties: |-
    ivo://ivoa.net/std/GMS#groups-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/GMS#search-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/GMS#search-1.0 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/UMS#users-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/UMS#reqs-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/UMS#login-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/UMS#modpass-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/UMS#resetpass-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/UMS#whoami-0.1 = {{ .Values.application.resourceID }}
    ivo://ivoa.net/std/CDP#delegate-1.0 = ivo://cadc.nrc.ca/cred
    ivo://ivoa.net/std/CDP#proxy-1.0 = ivo://cadc.nrc.ca/cred
    ca.nrc.cadc.reg.client.RegistryClient.baseURL = {{ required "ac: application.registryURL is required" .Values.application.registryURL }}

  catalina.properties: |-
    tomcat.connector.scheme={{ include "ac.tomcatConnectorScheme" . }}
    tomcat.connector.proxyName={{ include "ac.tomcatConnectorProxyName" . }}
    tomcat.connector.proxyPort={{ include "ac.tomcatConnectorProxyPort" . }}
    ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true
    ca.nrc.cadc.util.Log4jInit.messageOnly=true

  cadc-log.properties: |-
{{- range .Values.application.logging.users }}
    user = {{ . }}
{{- end }}
{{- range .Values.application.logging.usernames }}
    username = {{ . }}
{{- end }}
{{- range .Values.application.logging.groups }}
    group = {{ . }}
{{- end }}
