apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tomcat-svc
  namespace: {{ .Release.Namespace }}
  labels:
    run: {{ .Release.Name }}-tomcat-svc
spec:
  {{- with .Values.service.type }}
  type: {{ . }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    name: http-connection
    protocol: TCP
  {{- with .Values.service.extraPorts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    run: {{ .Release.Name }}-tomcat
