tomcat.connector.scheme=https
tomcat.connector.proxyName={{ .Values.deployment.hostname }}
tomcat.connector.proxyPort=443
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=true
ca.nrc.cadc.util.Log4jInit.messageOnly=true
# (default: ca.nrc.cadc.auth.NoOpIdentityManager)
ca.nrc.cadc.auth.IdentityManager=org.opencadc.auth.StandardIdentityManager

# database connection pools
{{- with required "PostgreSQL Database authentication configuration is required." .Values.postgresql.auth }}
org.opencadc.posix.mapper.maxActive={{ .maxActive | default 8 }}
org.opencadc.posix.mapper.username={{ .username | required "The postgresql.auth.username property cannot be empty." }}
org.opencadc.posix.mapper.password={{ .password | required "The postgresql.auth.password property cannot be empty." }}
org.opencadc.posix.mapper.url={{ .url | required "The postgresql.url property cannot be empty." }}
# {{- else }}
# org.opencadc.posix.mapper.url=jdbc:postgresql://posix-mapper-postgres.{{ $.Values.skaha.namespace }}.svc.{{ $.Values.kubernetesClusterDomain }}:5432/{{ .database }}
# {{- end }}
{{- end }}
