{{- include "access.validateRsaSignatureKeys" . }}
{{- if not .Values.rsaSignatureKeys.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "access.fullname" . }}-rsa-signature-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "access.labels" . | nindent 4 }}
type: Opaque
stringData:
  RsaSignaturePub.key: |
{{ .Values.rsaSignatureKeys.publicKey | trim | nindent 4 }}
  RsaSignaturePriv.key: |
{{ .Values.rsaSignatureKeys.privateKey | trim | nindent 4 }}
{{- end }}
