{{- include "access.validateRsaSignaturePublicKey" . }}
{{- $rk := .Values.rsaSignaturePublicKey | default dict }}
{{- if not $rk.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "access.fullname" . }}-rsa-signature-public-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "access.labels" . | nindent 4 }}
type: Opaque
stringData:
  RsaSignaturePub.key: |
{{ $rk.value | trim | nindent 4 }}
{{- end }}
