apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-add-user-config
  namespace: {{ .Release.Namespace }}
binaryData:
  desktop-config.tar:
    {{ .Files.Get "add-user-config/desktop-config.tar" | b64enc | nindent 4 }}
