# This file is used to create a namespace for the skaha sessions if it does not already exist.
{{- $wns := include "skaha.workloadNamespace" . }}
{{- if and $wns (not (eq $.Release.Namespace $wns)) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $wns }}
{{- end }}
