{{- if .Values.deployment.skaha.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.deployment.skaha.priorityClass.name | required "deployment.skaha.priorityClass.name is required when create is true" }}
  labels:
    {{- include "skaha.labels" $ | nindent 4 }}
value: {{ .Values.deployment.skaha.priorityClass.value }}
preemptionPolicy: {{ .Values.deployment.skaha.priorityClass.preemptionPolicy }}
globalDefault: {{ .Values.deployment.skaha.priorityClass.globalDefault }}
description: {{ .Values.deployment.skaha.priorityClass.description | quote }}
{{- end }}
{{- if .Values.deployment.skaha.headlessPriorityClass.create }}
{{- if .Values.deployment.skaha.priorityClass.create }}
---
{{- end }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.deployment.skaha.headlessPriorityClass.name | required "deployment.skaha.headlessPriorityClass.name is required when create is true" }}
  labels:
    {{- include "skaha.labels" $ | nindent 4 }}
value: {{ .Values.deployment.skaha.headlessPriorityClass.value }}
preemptionPolicy: {{ .Values.deployment.skaha.headlessPriorityClass.preemptionPolicy }}
globalDefault: {{ .Values.deployment.skaha.headlessPriorityClass.globalDefault }}
description: {{ .Values.deployment.skaha.headlessPriorityClass.description | quote }}
{{- end }}
