apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: skaha-tomcat
  name: skaha-tomcat
  namespace: {{ .Values.skaha.namespace }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      run: skaha-tomcat
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: skaha-tomcat
    spec:
{{- with .Values.deployment.skaha.nodeAffinity }}
      affinity:
        nodeAffinity:
{{ . | toYaml | indent 10 }}
{{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env: 
        - name: SKAHA_SESSIONS_HOSTNAME
          value: "{{ .Values.deployment.skaha.sessions.hostname | default .Values.deployment.hostname }}"
        - name: SKAHA_HOSTNAME
          value: "{{ .Values.deployment.hostname }}"
        - name: SKAHA_SESSIONS_TLD
          value: "{{ .Values.deployment.skaha.sessions.userStorageTopLevelDirectory | required "Missing deployment.skaha.sessions.userStorageTopLevelDirectory for User Sessions to mount the User Storage." }}"
        - name: SKAHA_SESSIONS_GPU_ENABLED
          value: "{{ .Values.deployment.skaha.sessions.gpuEnabled | default "false" }}"
        - name: SKAHA_USER_HOME_URI
          value: "{{ .Values.deployment.skaha.userHomeURI | required "Missing deployment.skaha.userHomeURI.  This is necessary for new user allocations to be put through Cavern" }}"
        - name: SKAHA_CAVERN_SERVICE_URI
          value: "{{ .Values.deployment.skaha.cavernServiceURI | required "Missing deployment.skaha.cavernServiceURI.  This is necessary for new user allocations to be put through Cavern" }}"
        - name: SKAHA_WORKLOAD_NAMESPACE
          value: "{{ .Values.skahaWorkload.namespace }}"
        - name: SKAHA_SESSIONS_MAX_COUNT
          value: "{{ .Values.deployment.skaha.sessions.maxCount }}"
        - name: SKAHA_SESSIONS_EXPIRY_SECONDS
          value: "{{ .Values.deployment.skaha.sessions.expirySeconds }}"
        - name: SKAHA_DEFAULT_STORAGE_QUOTA_GB
          value: "{{ .Values.deployment.skaha.defaultQuotaGB }}"
        - name: SKAHA_SESSIONS_IMAGE_REGISTRY_HOSTS
          value: "{{ .Values.deployment.skaha.sessions.imageRegistryHosts }}"
        - name: SKAHA_USERS_GROUP
          value: "{{ .Values.deployment.skaha.usersGroup }}"
        - name: SKAHA_HEADLESS_GROUP
          value: "{{ .Values.deployment.skaha.headlessGroup }}"
        {{- with .Values.deployment.skaha.headlessPriorityGroup }}
        - name: SKAHA_HEADLESS_PRIORITY_GROUP
          value: "{{ . }}"
        {{- end }}
        {{- with .Values.deployment.skaha.headlessPriorityClass }}
        - name: SAKAHA_HEADLESS_PRIORITY_CLASS
          value: "{{ . }}"
        {{- end }}
        {{- with .Values.deployment.skaha.sessions.queue }}
        {{- range $queueConfigKey, $queueConfig := . }}
        - name: SKAHA_QUEUE_{{ $queueConfigKey | upper }}_NAME
          value: "{{ $queueConfig.queueName | required (printf "Missing .Values.deployment.skaha.sessions.queue.%s.queueName" $queueConfigKey) }}"
        - name: SKAHA_QUEUE_{{ $queueConfigKey | upper }}_PRIORITY_CLASS
          value: "{{ $queueConfig.priorityClass | required (printf "Missing .Values.deployment.skaha.sessions.queue.%s.priorityClass" $queueConfigKey) }}"
        {{- end }}
        {{- end }}
        - name: SKAHA_ADMINS_GROUP
          value: "{{ .Values.deployment.skaha.adminsGroup }}"
        - name: SKAHA_POSIX_MAPPER_RESOURCE_ID
          value: "{{ .Values.deployment.skaha.posixMapperResourceID }}"
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis-master.{{ .Values.skaha.namespace }}.svc.{{ .Values.kubernetesClusterDomain }}"
        - name: REDIS_PORT
          value: "6379"
        {{- with .Values.deployment.skaha.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.deployment.skaha.image }}
        imagePullPolicy: {{ .Values.deployment.skaha.imagePullPolicy }}
        name: skaha-tomcat
        resources:
          requests:
            memory: {{ .Values.deployment.skaha.resources.requests.memory }}
            cpu: {{ .Values.deployment.skaha.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.skaha.resources.limits.memory }}
            cpu: {{ .Values.deployment.skaha.resources.limits.cpu }}
        ports: 
        - containerPort: 8080
          protocol: TCP
        {{- with .Values.deployment.skaha.extraPorts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: "/config"
          name: config-volume
        {{- with .Values.deployment.skaha.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
{{- with .Values.deployment.extraHosts }}
      hostAliases:
{{- range $extraHost := . }}
        - ip: {{ $extraHost.ip }}
          hostnames:
            - {{ $extraHost.hostname }}
{{- end }}
{{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.deployment.skaha.priorityClassName }}
      serviceAccountName: {{ .Values.deployment.skaha.serviceAccountName }}
      volumes:
      - name: config-volume
        configMap:
          name: skaha-config
       {{- with .Values.deployment.skaha.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
