name: Release Please

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: ${{ github.repository == 'opencadc/deployments' }}
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
